name: PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ask-questions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Install dependencies
      run: npm install
    - name: Ask questions
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node scripts/checklist.js ${{ github.event.pull_request.head.sha }} ${{ github.event.number }}