name: PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }} 
    - name: Install dependencies
      run: ls -ltra && npm install
    - name: Run checklist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  npm run checklist ${{ github.event.pull_request.head.sha }} ${{ github.event.number }}